[
    {
        "id": 4,
        "first_name": "Amine",
        "last_name": "Ben Makhlouf",
        "email": "amin.benmakhlouf@gmail.com",
        "password": "$2b$12$LaobS./h20hNG7G/x8F1TO93g/HWVhGL.I1bLB0t0EGjntuOSsDlC",
        "created_at": datetime.datetime(2023, 7, 31, 20, 1, 22),
        "updated_at": datetime.datetime(2023, 7, 31, 20, 1, 22),
        
        "tranfert_messages.id": 3,
        "sender_id": 5,
        "receiver_id": 4,
        "message": "bonjour papa cv",
        "tranfert_messages.created_at": datetime.datetime(2023, 7, 31, 20, 6, 14),
        "tranfert_messages.updated_at": datetime.datetime(2023, 7, 31, 20, 6, 14),
        
        "sender.id": 5,
        "sender.first_name": "Med Yassine",
        "sender.last_name": "Ben M.",
        "sender.email": "medyassine.bm@gmail.com",
        "sender.password": "$2b$12$tpEILH5QP36HicIfsOgJyegQ31EtwNLtKVefz6uVfJLVibFr129yi",
        "sender.created_at": datetime.datetime(2023, 7, 31, 20, 2, 3),
        "sender.updated_at": datetime.datetime(2023, 7, 31, 20, 2, 3),
    },
    {
        "id": 4,
        "first_name": "Amine",
        "last_name": "Ben Makhlouf",
        "email": "amin.benmakhlouf@gmail.com",
        "password": "$2b$12$LaobS./h20hNG7G/x8F1TO93g/HWVhGL.I1bLB0t0EGjntuOSsDlC",
        "created_at": datetime.datetime(2023, 7, 31, 20, 1, 22),
        "updated_at": datetime.datetime(2023, 7, 31, 20, 1, 22),
        
        "tranfert_messages.id": 4,
        "sender_id": 7,
        "receiver_id": 4,
        "message": "bonjour papa winek taw?",
        "tranfert_messages.created_at": datetime.datetime(2023, 7, 31, 20, 6, 14),
        "tranfert_messages.updated_at": datetime.datetime(2023, 7, 31, 20, 6, 14),
        
        "sender.id": 7,
        "sender.first_name": "Med Sadok",
        "sender.last_name": "Ben Makhlouf",
        "sender.email": "medsadok.benmakhlouf@gmail.com",
        "sender.password": "$2b$12$2pRe/0irdOaPcp2oOpck/ut1Me3cE5Ue2MGBzwZ0wG2wLsQbzFoTm",
        "sender.created_at": datetime.datetime(2023, 7, 31, 20, 2, 44),
        "sender.updated_at": datetime.datetime(2023, 7, 31, 20, 2, 44),
    },
]
